- hosts: all
  become: true
  tasks:
    - name: install httpd package
      yum:
        name: httpd
        state: present
    - name: install mysql
      yum:  
        name: mariadb-server
        update_cache: yes
