- hosts: all
  become: true
  tasks:
  - name: http-package and php-pack
    package:
      name:
        - "{{ apache_package}}"
        - "{{ php_package}}"
      state: latest
      update_cache: yes    
            
